### ISSUE TITLE
IPO test fail with R3.2.0 (2015-04-16)

### ISSUE THREAD

**Issue by tobigithub** [rietho/IPO#12]
Hi,
I try to run the IPO code from folder test:
- library("msdata")
- BiocGenerics:::testPackage("IPO")

> BiocGenerics:::testPackage("IPO")
> Error: package ‘BiocGenerics’ was built before R 3.0.0: please re-install it
> 
> setRepositories()
> install.packages("BioGenerics")
> Warning message:
> package ‘BioGenerics’ is not available (for R version 3.2.0) 

just to let you know.
Tobias

**Comment by glibiseller** [comment]
Hi,

If "BiocGenerics:::testPackage("IPO")" does not work you can find the actual test-script under https://github.com/glibiseller/IPO/tree/master/inst/unitTests.

What does your sessionInfo() return? I get BiocGenerics_0.14.0 within "other attached packages".

best regards,
Gunnar

**Comment by tobigithub** [comment]
Hi,
actually until somebody can show that for all R version clean
installations work, I suspect IPO will only work with specific R versions.
The good thing is IPO runs under WINDOWS XP with R3.03 see:
https://github.com/glibiseller/IPO/issues/16

I tried a number of packages starting in R2, R3.0 R3.2 etc under WIN7 and most of
them give errors the one way or the other, I am quite sure R experts can
solve many of the issues, common R users not that easy.

After removing the complete R-directory and R-library and a complete 
reinstall with this old R3.2.0 version I got this additional error below.
These errors come and go and change from time to time. Its R, 
basically reminds me of the "DLL hell" from Windows.


--
* installing *source* package 'IPO' ...
** R
** inst
** tests
** preparing package for lazy loading
Warning: package 'Rcpp' was built under R version 3.2.2
Warning in fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.11.6)
than is installed on your system (0.12.0). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
Warning: package 'rsm' was built under R version 3.2.2
Warning: package 'CAMERA' was built under R version 3.2.1
Warning: package 'igraph' was built under R version 3.2.2
Error : .onLoad failed in loadNamespace() for 'CAMERA', details:
  call: .setCAMERAOptions(pkgname)
  error: 4 arguments passed to .Internal(nchar) which requires 3
Error : package 'CAMERA' could not be loaded
ERROR: lazy loading failed for package 'IPO'
--

I think one would need to built a tree with all R versions
and then always test and update that with all current packages.
Unit testing and dependency testing is quite common in other "languages",
its probably not very common for R where every month or so a new version
comes out.  Well now its the "R dependency hell".
http://blog.revolutionanalytics.com/2014/10/introducing-rrt.html


Cheers
Tobias

**Comment by glibiseller** [comment]
Hi,

thanks Tobias for testing all these different R versions. At the moment I'm only running R 3.2.1 on Win7 and Linux which works fine. 

I always wait some time before installing the newest R-version exactly because of these dependencies. 

Maybe it would be good to add system-setups that work to the readme-file at https://github.com/glibiseller/IPO.

What do you think?
Cheers
Gunnar

**Comment by tobigithub** [comment]
Hi,
Its a good idea to keep a log of confirmed versions, 
I also confirmed WIN7, R3.1.2, IPO works.
In principle it could also go into the IPO WIKI
https://github.com/glibiseller/IPO/wiki
Cheers
Tobias

**Comment by glibiseller** [comment]
Hi,

good idea. I already created a wiki-page regarding system-configurations. https://github.com/glibiseller/IPO/wiki/known-working-system-configurations

Do you have a WIN7 32 or 64 bit installation?

Maybe we could keep this issue open so people can post their working configurations?

Cheers,
Gunnar

**Comment by sneumann** [comment]
This seems to be an issue specific to R-3.2.0 as mentioned here:
https://stackoverflow.com/questions/30955508/r-cannot-load-package-forecast-due-to-namespace-error/30956549#30956549
