### ISSUE TITLE
Image folder for WIKI pages

### ISSUE THREAD

**Issue by tobigithub** [rietho/IPO#24]
Hi,
just a question, can you create a image folder for the IPO WIKI so I can upload pictures to the WIKI without creating pull requests from my fork all the time, I basically would like to fully edit the original WIKI with pictures. Not sure if this is commonly done in this way and OK.

![ipo-threading-win](https://cloud.githubusercontent.com/assets/2569565/9455778/9c4b0c7a-4a83-11e5-8045-a44f26befd79.png)

Cheers
Tobias

**Comment by glibiseller** [comment]
Hi,

Thanks for adding the additional pages and improving the wiki. The wiki itself is a github repository which you can access from https://github.com/glibiseller/IPO.wiki.git. There, I already created a folder "images" where we could store pictures in the future. However, it seems like only collaborators are allowed to upload there. I wouldn't mind making you a collaborator though.

A second solution would be to simply add images to this issue and reference them in the wiki!

What do you think?

Cheers
Gunnar

**Comment by tobigithub** [comment]
Hi,
no I can not access that dir (https://github.com/glibiseller/IPO.wiki.git.) 
I will just text if needed. Its a GitHub thing.
http://mikehadlow.blogspot.com/2014/03/how-to-add-images-to-github-wiki.html

Cheers
Tobias

**Comment by glibiseller** [comment]
Hi,
You'll have to create a new repository only for the wiki with the address https://github.com/glibiseller/IPO.wiki.git to be able to see the images folder I created there. 
There's already an example picture uploaded. 

<a href="url"><img src="https://raw.githubusercontent.com/wiki/glibiseller/IPO/images/toc.jpg"  height="141" width="250" ></a>

Unfortunately it has the same permission as the IPO-repository therefore not everyone can upload images :disappointed:

**Comment by tobigithub** [comment]
Tnx!
