### ISSUE TITLE
Update install guide

### ISSUE THREAD

**Issue by mhische-md** [rietho/IPO#41]
When following the current [ installation instruction](https://github.com/rietho/IPO/blob/master/vignettes/IPO.Rmd), the line `install_github("glibiseller/IPO") `
threw this error: 
`Downloading GitHub repo glibiseller/IPO@master
Fehler in curl::curl_fetch_memory(url, handle = handle) :
  Couldn't resolve host name`

However, `install_github("rietho/IPO") ` worked fine.
So I guess, the instruction needs a little update.

**Comment by rietho** [comment]
Thanks for the hint.
