### ISSUE TITLE
MacOSX: Different results for xcmsSet.centWave.mzdiff

### ISSUE THREAD

**Issue by lecorguille** [rietho/IPO#42]
Hi,
Because I'm working on the IPO Galaxy wrappers. I set some functional tests so I often launch IPO with the same set of inputs and parameters.

First of all, note that I get this behaviour on a Mac.

And maybe it's completely normal but I get different results for this value `xcmsSet.centWave.mzdiff` sometimes I get `0.01` and sometimes I get `-0.001`.

I thought that was because I was loading or not snow at the beginning of my script?
But I also got this switch when I just add or not a print(sessionInfo()) before IPO functions.

Meanwhile, it is stable at `0.01` under Linux and through my TravisCI. So it's not a big deal because Linux is my target. But I would like to share this experience.

**Comment by rietho** [comment]
Thanks for sharing your experience.

That's an interesting behavior. I'd expect that the PPS value for your case is the same for both `xcmsSet.centWave.mzdiff` outcomes. Is that true?
In this case I'd believe that there are some functions underlying some randomness on Mac, but not on Linux.

**Comment by lecorguille** [comment]
Sorry, but what is PPS?

**Comment by rietho** [comment]
The PPS is the Peack-Picking-Score that is used as objective for the peack-picking optimization (see our [paper](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0562-8) for more details).

IPO is now also available through the development version of Bioconductor. In the [vignette](http://bioconductor.org/packages/devel/bioc/vignettes/IPO/inst/doc/IPO.html) on Biocondcutor you can see how to get the PPS value of an optimized peak-picking (just search for PPS xset in the vignette).

**Comment by lecorguille** [comment]
I can't find this new version of the vignette into this repo.
Is there an other place for IPO code?

**Comment by rietho** [comment]
This repo will stay the the place for the IPO code.
I have not pushed the preparation for bioconductor before, but now there is a branch called [biocprep](https://github.com/rietho/IPO/tree/biocprep) with all preparations for biocondcutor. Nevertheless the vignette here is not knitted. But you can find the vignette with all R output on bioconductor development version http://bioconductor.org/packages/devel/bioc/html/IPO.html
