### ISSUE TITLE
limit optimizeRetGroup() to group.density

### ISSUE THREAD

**Issue by sneumann** [rietho/IPO#5]
Hi,
currently, optimizeRetGroup() optimises all parameters 
for all group() methods. It would be great if the method(s)
could be restricted, e.g. retcorGroupParameters$groupMethod=c("density", "obiwarp")
or just retcorGroupParameters$groupMethod="density"
Yours, Steffen

**Comment by glibiseller** [comment]
The function getDefaultRetGroupStartingParams has now a parameter retcorMethod which lets you choose "obiwarp", "loess" and "none" (if you dont want retention time correction done)

Does this change satisfy this issue?

Yours, Gunnar

**Comment by rietho** [comment]
@sneumann Is there still something to do?
