### ISSUE TITLE
Exponent for GRTS as ?

### ISSUE THREAD

**Issue by sneumann** [rietho/IPO#9]
Hi, currently, RT deviations are added up linearly. Possibly, an exponent might make sense, 
which punishes values for span=X which cause overcorrection. Yours, Steffen

**Comment by glibiseller** [comment]
Hi,

Thanks for the suggestion. I'll make some tests to see how it works.

Cheers
Gunnar

**Comment by rietho** [comment]
@sneumann I'm not sure, if this is still an issue?!
